[project]
name = "agentzoo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "openai>=1.82.0",
    "openai-agents>=0.0.16",
    "tqdm>=4.67.1",
]
